# System logging
systemLog:
  destination: file
  path: "C:\\data\\log\\mongod.log"
  logAppend: true
  verbosity: 0

# Storage options
storage:
  dbPath: "C:\\data\\mongodb"

# Network options
net:
  bindIp: 0.0.0.0
  port: 27018
  maxIncomingConnections: 200
  tls:
    mode: requireTLS
    certificateKeyFile: "C:\\data\\mongo-server1.pem"
    CAFile: "C:\\data\\test-ca.pem"

# Security options
security:
  authorization: enabled

# Parameters
setParameter:
  enableLocalhostAuthBypass: false
